### ISSUE TITLE
Add list of hosts into Subnetworkv4

### ISSUE THREAD

**Issue by Mat3oo** [Projekt-zespolowy-TIU/DesignYourNetwork#17]
Host's properties:
- number
- name
- Ip

**Comment by Flaysen** [comment]
Subnet name

**Comment by Mat3oo** [comment]
At this moment Subnet has its name, and my point is that each Subnet will also contain list/vector of hosts.
So if u access concrete Subnet, u can iterate through it's hosts and display their properties. Does that sound clear and sensible?
